# Day 08. Exercise 04
# Regression

## 0. Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Preprocessing

1. Read the file [`checker_regression.csv`](https://drive.google.com/file/d/1L8auBzJEghWFewznhhFpcrqxW4GqcfRY/view?usp=sharing).
2. Fill the missing values in it with `0`.
3. Make a split of your dataset on train and test with parameters `test_size=0.2`.

In [3]:
df = pd.read_csv('../../datasets/checker_regression.csv')
df.head()

      uid  num_commits  pageviews  AVG(diff)
0  user_1           62       28.0        NaN
1  user_1           62       28.0        NaN
2  user_1           62       28.0        NaN
3  user_1           62       28.0        NaN
4  user_1           62       28.0        NaN

In [6]:
df.fillna(0, inplace=True)
df.head()

      uid  num_commits  pageviews  AVG(diff)
0  user_1           62       28.0        0.0
1  user_1           62       28.0        0.0
2  user_1           62       28.0        0.0
3  user_1           62       28.0        0.0
4  user_1           62       28.0        0.0

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='AVG(diff)')
y = df['AVG(diff)']

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=21)

## 2. Crossvalidation

1. Write a function `crossval` that takes as arguments: `n_splits` for `KFold()`, `X`, `y`, model instantiated class with the parameters of the model (keep in mind: `random_state=21`) and returns for a given model class a result like this:

```
train -  2696.4496895424836   |   test -  1589.9979527104958
train -  2660.957874001452   |   test -  2075.102636027137
train -  2847.315529246795   |   test -  320.911928168403
train -  2500.7691099659237   |   test -  4132.461382030178
train -  2643.927917295123   |   test -  2237.8140952197878
train -  2396.295678819444   |   test -  4509.650064742476
train -  2003.402267924976   |   test -  8403.491474908551
train -  2531.876094212613   |   test -  3135.944102735099
train -  2683.1795186023123   |   test -  1796.01426292594
train -  2537.1192483996338   |   test -  3439.29824116941
Average RMSE on crossval is 3164.0686140637476
```

2. Run the function for `LinearRegression`, `DecisionTreeRegressor`, `RandomForestRegressor`. You may choose the parameters by yourself, but find the good enough for you.

## 3. Predictions and evaluation

1. Make predictions for the test dataset using each of the three models with the finalized parameters.
2. Draw a plot for each of the models where the `x-axis` is the actual average difference and the `y-axis` is the prediction made by a model.
3. How would plot look like in the ideal case? Put the answer to the markdown cell in the end of the section.