In [22]:
import pandas as pd

In [23]:
df = pd.read_json('../../data/auto.json')
df.set_index('CarNumber', inplace=True)

In [24]:
filter_fines_2100 = df[df['Fines'] > 2100]
filter_fines_2100

               ID  Refund         Fines        Make    Model
CarNumber
Y163O8161RUS    0       2   3200.000000        Ford    Focus
E432XX77RUS     1       1   6500.000000      Toyota    Camry
92918M178RUS    5       1   5700.000000        Ford    Focus
H234YH197RUS   10       2   6000.000000        Ford    Focus
E40577152RUS   11       1   8594.586466        Ford    Focus
...           ...     ...           ...         ...      ...
O718MM163RUS  923       2   8594.586466        Ford    Focus
7065C8197RUS  924       2  11400.000000  Volkswagen   Passat
O22097197RUS  925       1  24300.000000        Ford    Focus
M0309X197RUS  927       1  22300.000000        Ford    Focus
H419XE197RUS  930       2   8594.586466      Toyota  Corolla

[455 rows x 5 columns]

In [25]:
filter_fines_n_refund = df[(df['Fines'] > 2100) & (df['Refund'] == 2)]
filter_fines_n_refund

               ID  Refund         Fines        Make    Model
CarNumber
Y163O8161RUS    0       2   3200.000000        Ford    Focus
H234YH197RUS   10       2   6000.000000        Ford    Focus
707987163RUS   12       2   2200.000000        Ford    Focus
K330T8197RUS   13       2   8200.000000       Skoda  Octavia
M592CH197RUS   17       2   8594.586466       Skoda  Octavia
...           ...     ...           ...         ...      ...
O136HO197RUS  921       2   7800.000000      Toyota  Corolla
O68897197RUS  922       2  12300.000000        Ford    Focus
O718MM163RUS  923       2   8594.586466        Ford    Focus
7065C8197RUS  924       2  11400.000000  Volkswagen   Passat
H419XE197RUS  930       2   8594.586466      Toyota  Corolla

[309 rows x 5 columns]

In [26]:
model_list = ['Focus', 'Corolla']
filter_model = df[df['Model'].isin(model_list)]
filter_model

               ID  Refund         Fines    Make    Model
CarNumber
Y163O8161RUS    0       2   3200.000000    Ford    Focus
7184TT36RUS     2       1   2100.000000    Ford    Focus
X582HE161RUS    3       2   2000.000000    Ford    Focus
92918M178RUS    5       1   5700.000000    Ford    Focus
H234YH197RUS   10       2   6000.000000    Ford    Focus
...           ...     ...           ...     ...      ...
Y163O8161RUS  926       2   1600.000000    Ford    Focus
M0309X197RUS  927       1  22300.000000    Ford    Focus
O673E8197RUS  928       2    600.000000    Ford    Focus
8610T8154RUS  929       1   2000.000000    Ford    Focus
H419XE197RUS  930       2   8594.586466  Toyota  Corolla

[593 rows x 5 columns]

In [30]:
CarNumber_list = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
filter_CarNumber = df.loc[CarNumber_list]
filter_CarNumber

               ID  Refund          Fines  Make  Model
CarNumber
Y7689C197RUS  272       1   27000.000000  Ford  Focus
Y7689C197RUS  730       2    9000.000000  Ford  Focus
Y7689C197RUS  753       2   45000.000000  Ford  Focus
Y7689C197RUS  870       1   36000.000000  Ford  Focus
92928M178RUS   43       1    8594.586466  Ford  Focus
92928M178RUS  283       1     600.000000  Ford  Focus
92928M178RUS  653       1    1200.000000  Ford  Focus
92928M178RUS  879       2    3000.000000  Ford  Focus
7788KT197RUS  107       2   12000.000000  Ford  Focus
7788KT197RUS  423       2    8594.586466  Ford  Focus
7788KT197RUS  540       1   20000.000000  Ford  Focus
7788KT197RUS  755       2    4000.000000  Ford  Focus
H115YO163RUS   52       1    2200.000000  Ford  Focus
H115YO163RUS  326       1    8594.586466  Ford  Focus
H115YO163RUS  410       2    1100.000000  Ford  Focus
X758HY197RUS  147       2   24200.000000  Ford  Focus
X758HY197RUS  237       2   72600.000000  Ford  Focus
X758HY197RUS  570       2  145200.000000  Ford  Focus

In [31]:
median_fines_by_make = df.groupby('Make')['Fines'].median()
print(median_fines_by_make)

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [32]:
median_fines_by_make_model = df.groupby(['Make', 'Model'])['Fines'].median()
print(median_fines_by_make_model)

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

In [33]:
count_fines_by_make_model = df.groupby(['Make', 'Model'])['Fines'].count()
print(count_fines_by_make_model)

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

In [34]:
min_max_fines_by_make_model = df.groupby(['Make', 'Model'])['Fines'].agg(['min', 'max'])
print(min_max_fines_by_make_model)

                       min            max
Make       Model
Ford       Focus     100.0  180000.000000
           Mondeo   1100.0   46200.000000
Skoda      Octavia   300.0  145000.000000
Toyota     Camry     500.0   22400.000000
           Corolla   900.0   34300.000000
Volkswagen Golf      200.0  168000.000000
           Jetta     500.0   46000.000000
           Passat    100.0   29700.000000
           Touareg   500.0    8594.586466

In [35]:
std_fines_by_make_model = df.groupby(['Make', 'Model'])['Fines'].std()
print(std_fines_by_make_model)

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

In [36]:
fines_count_by_car = df.groupby('CarNumber')['Fines'].count().sort_values(ascending=False)
print(fines_count_by_car)

CarNumber
Y7689C197RUS    4
7788KT197RUS    4
92928M178RUS    4
Y7129Y50RUS     3
X758HY197RUS    3
               ..
Y967O8197RUS    1
Y965O8197RUS    1
Y965EE197RUS    1
Y964O8197RUS    1
Y964EE197RUS    1
Name: Fines, Length: 531, dtype: int64

In [37]:
top_violator = fines_count_by_car.index[0]
top_violator_rows = df.loc[top_violator]
print(top_violator_rows)

               ID  Refund    Fines  Make  Model
CarNumber
Y7689C197RUS  272       1  27000.0  Ford  Focus
Y7689C197RUS  730       2   9000.0  Ford  Focus
Y7689C197RUS  753       2  45000.0  Ford  Focus
Y7689C197RUS  870       1  36000.0  Ford  Focus

In [38]:
fines_sum_by_car = df.groupby('CarNumber')['Fines'].sum().sort_values(ascending=False)
print(fines_sum_by_car)

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
Y166O8161RUS       100.0
K326T8197RUS       100.0
Y195O8161RUS       100.0
C58078163RUS       100.0
705787163RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [39]:
top_payer = fines_sum_by_car.index[0]
top_payer_rows = df.loc[top_payer]
print(top_payer_rows)

               ID  Refund     Fines  Make  Model
CarNumber
X758HY197RUS  147       2   24200.0  Ford  Focus
X758HY197RUS  237       2   72600.0  Ford  Focus
X758HY197RUS  570       2  145200.0  Ford  Focus

In [46]:
car_model_variants = df.groupby('CarNumber')['Model'].apply(lambda x: set(x))
multiple_models = car_model_variants[car_model_variants.apply(len) > 1]
print(multiple_models)

CarNumber
E316EH197RUS    {Touareg, None}
Name: Model, dtype: object